### ISSUE TITLE
TypeError: Cannot set property '__options__' of undefined

### ISSUE THREAD

**Issue by robogeek** [nodeca/embedza#6]
I'm trying out this module and ran into that error message.  The script is a simple modification of the example you give in the project:

```
var embedza = require('embedza')({});
 
embedza.render(process.argv[2], 'block')
  .then(result => {
    if (result) {
	console.log(result.html, result.type);
	console.log(JSON.stringify(result));
    }
  });
```

I've tried this with Node 6.9 and 7.10 with the same results

```
$ node e 'https://www.youtube.com/watch?v=kPaveQftN2I'
/Users/david/ws/techsparx.com/node_modules/embedza/lib/index.js:43
  this.__options__ = _.merge({
                   ^

TypeError: Cannot set property '__options__' of undefined
    at Embedza (/Users/david/ws/techsparx.com/node_modules/embedza/lib/index.js:43:20)
    at Object.<anonymous> (/Users/david/ws/techsparx.com/e.js:1:95)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
```

So ... at that line, `this` is `undefined`?  That doesn't quite make sense, but that's what is implied.

**Comment by puzrin** [comment]
`var embedza = require('embedza')({});` <- you've missed `new`

**Comment by robogeek** [comment]
I simply copy/paste'd your example.  Is this what you meant?  If so you should update your example code:

```
const Embedza = require('embedza');
var embedza = new Embedza({});
 
embedza.render(process.argv[2], 'block')
  .then(result => {
    if (result) {
	console.log(result.html, result.type);
	console.log(JSON.stringify(result));
    }
  });
```

That does work ...

**Comment by puzrin** [comment]
Yes.

Typo in example.
